version: "3.3"
services:
  # WebServer config
  webserver:
    build: .
    ports:
      - "6354:80"
    depends_on:
      - redis

  # Redis config
  redis:
    image: redis:4.0
    # volumes_from:
    #   - webserver
